# Agenda:


## variable length keyword arguments

### when we define a function we can use wild cards:

     Wild cards  *  &  * *

1. Non keyword argument  * ( just values pass not fixed)

2. Keyword arguments  * *  (key value and data value passed)

# using *

       def f1(*t): # tuple

         ....

         ....
      
       f1(4,5,6,7,)

 # using * *

       def f2(**d): # dict

         ....

         ....


        f2(a = 2 , b= 5 , c = 6)

# example

In [2]:
def f1(**d):
  for k, v in d.items():

    print(k, "-", v)

f1(a= 2, b = 4, d=6, e = 8) # passing the arguemnts

a - 2
b - 4
d - 6
e - 8

In [4]:
def f1(**d):
  for k, v in d.items():

    print(k, "-", v)

f1(name = "suleman", age= 24) # passing the arguemnts

f1(name = "suleman", age= 24, gender ="male")

f1(name = "suleman", age= 24, email= "44cs@gmail.com")

name - suleman
age - 24
name - suleman
age - 24
gender - male
name - suleman
age - 24
email - 44cs@gmail.com

# passing arguments

### using non keyword

In [6]:
def f1(*t):

  print(t)

t1 = (2,4,6,8,24) # it is a tuple

f1(t1) # with-out * here  the t1 elements are not the t tuple ements

# and t1 become a tuple element of a tuple

((2, 4, 6, 8, 24),)

In [7]:
def f1(*t):

  print(t)

t1 = (2,4,6,8,24)

f1(*t1) # with * and now the t1 elements become the t tuple ements

(2, 4, 6, 8, 24)

# using keyword arguemnts

In [9]:
def f1(**d):
  for k, v in d.items():

    print(k, "-", v)

d1={'a':2,'b':4,"c":6}

f1(d1) # f1 not taking a positional arguemnt and we have passed 1 argument

TypeError: f1() takes 0 positional arguments but 1 was given

In [10]:
def f1(**d):
  for k, v in d.items():

    print(k, "-", v)

d1={'a':2,'b':4,"c":6}

f1(**d1)

a - 2
b - 4
c - 6